### ISSUE TITLE
在我博客上并未看到“下一页”之类的链接，怎么回事？

### ISSUE THREAD

**Issue by luckypoem** [hanxi/issues-blog#1]
hi/

按照你的这个repo,我搭建了博客http://hib.bright.biz.st/ ，不过为何http://hib.bright.biz.st/?p=1 不显示在首页？我设置了per_page的值为3，不过在我博客上并未看到“下一页”之类的链接，怎么回事？

**Comment by hanxi** [comment]
没有下一页这功能。参数p对应issues 的id

**Comment by hanxi** [comment]
有加载更多的功能

**Comment by briteming** [comment]
hi.

我也搭建了你这个博客程序: https://briteming.github.io/issues-blog/ ,但是首页里没有显示“加载更多”。如何解决？
谢谢回复。

<img width="956" height="406" alt="Image" src="https://github.com/user-attachments/assets/85377a68-7c8e-4301-a09e-88d7f91b6f44" />

**Comment by hanxi** [comment]
应该是bug 。 https://github.com/hanxi/issues-blog/blob/gh-pages/app.js#L50

**Comment by briteming** [comment]
哦，那么如何解决这个bug?

**Comment by hanxi** [comment]
试试 GitHub Copilot？

**Comment by hanxi** [comment]
让ai改了下，不知道修复了没
